name: Griefus
main: net.coreprotect.CoreProtect
version: ${project.version}
branch: ${project.branch}
api-version: 1.16
folia-supported: true
website: https://griefus.zhdev.org
authors: [Intelli, rozhur]
softdepend: [WorldEdit]
description: >
             Provides block protection for your server.
commands:
  co:
    description: Utilize the plugin
    permission: griefus.co
    permission-message: §3Griefus §f- You do not have permission to do that.
    usage: /<command> <params>
  core:
    description: Utilize the plugin
    permission: griefus.core
    permission-message: §3Griefus §f- You do not have permission to do that.
    usage: /<command> <params>
  coreprotect:
    description: Utilize the plugin
    permission: coreprotect.coreprotect
    permission: griefus.coreprotect
    permission-message: §3Griefus §f- You do not have permission to do that.
    usage: /<command> <params>
  gr:
    description: Utilize the plugin
    permission: griefus.gr
    permission-message: §3Griefus §f- You do not have permission to do that.
    usage: /<command> <params>
  grief:
    description: Utilize the plugin
    permission: griefus.grief
    permission-message: §3Griefus §f- You do not have permission to do that.
    usage: /<command> <params>
  griefus:
    description: Utilize the plugin
    permission: griefus.griefus
    permission-message: §3Griefus §f- You do not have permission to do that.
    usage: /<command> <params>
  gri:
    description: Inspector mode shortcut
    permission: griefus.inspect
    permission-message: §3Griefus §f- You do not have permission to do that.
    usage: /<command> <params>
permissions:
    griefus.*:
        description: Gives access to all Griefus actions and commands
        default: op
        children: 
            griefus.rollback: true
            griefus.restore: true
            griefus.inspect: true
            griefus.help: true
            griefus.purge: true
            griefus.lookup: true
            griefus.lookup.near: true
            griefus.lookup.chat: true
            griefus.lookup.command: true
            griefus.lookup.session: true
            griefus.lookup.username: true
            griefus.lookup.block: true
            griefus.lookup.sign: true
            griefus.lookup.click: true
            griefus.lookup.container: true
            griefus.lookup.inventory: true
            griefus.lookup.item: true
            griefus.lookup.kill: true
            griefus.teleport: true
            griefus.reload: true
            griefus.status: true
            griefus.consumer: true
            griefus.networking: true
            griefus.give: false
    griefus.co:
        description: Has permission to access the Griefus /co command
        default: true
    griefus.core:
        description: Has permission to access the Griefus /core command
        default: false
    griefus.coreprotect:
        description: Has permission to access the Griefus /coreprotect command
        default: false
    griefus.lookup:
        description: Has permission to use the lookup command
        default: op
        children:
            griefus.lookup.near: true
            griefus.lookup.chat: true
            griefus.lookup.command: true
            griefus.lookup.session: true
            griefus.lookup.username: true
            griefus.lookup.block: true
            griefus.lookup.sign: true
            griefus.lookup.click: true
            griefus.lookup.container: true
            griefus.lookup.inventory: true
            griefus.lookup.item: true
            griefus.lookup.kill: true
    griefus.lookup.near:
        description: Has permission to lookup nearby changes via the near command
        default: op
    griefus.lookup.chat:
        description: Has permission to lookup chat messages
        default: op
    griefus.lookup.command:
        description: Has permission to lookup player commands
        default: op
    griefus.lookup.session:
        description: Has permission to lookup player sessions
        default: op
    griefus.lookup.username:
        description: Has permission to lookup player username changes
        default: op
    griefus.lookup.block:
        description: Has permission to lookup block data
        default: op
    griefus.lookup.sign:
        description: Has permission to lookup sign messages
        default: op
    griefus.lookup.click:
        description: Has permission to lookup player interactions
        default: op
    griefus.lookup.container:
        description: Has permission to lookup container transactions
        default: op
    griefus.lookup.inventory:
        description: Has permission to lookup inventory transactions
        default: op
    griefus.lookup.item:
        description: Has permission to lookup item transactions
        default: op
    griefus.lookup.kill:
        description: Has permission to lookup entity kills
        default: op
    griefus.rollback:
        description: Has permission to perform rollbacks
        default: op
    griefus.restore:
        description: Has permission to perform restores
        default: op
    griefus.inspect:
        description: Has permission to use the inspector
        default: op
    griefus.help:
        description: Has permission to use the help command
        default: op
    griefus.purge:
        description: Has permission to use the purge command
        default: op
    griefus.teleport:
        description: Has permission to use the teleport command
        default: op
    griefus.reload:
        description: Has permission to use the reload command
        default: op
    griefus.status:
        description: Has permission to use the status command
        default: op
    griefus.consumer:
        description: Has permission to use the consumer command
        default: op
    griefus.networking:
        description: Has permission to use the networking API
        default: op
    griefus.give:
        description: Has permission to use the give command
        default: false
